### PR TITLE
Fix some errors not being shown and erroring when no config file is found

### LINKED ISSUE #262: sops encrypt not returning anything
I installed sops on MacOS using

`$ go get -u go.mozilla.org/sops/cmd/sops`

I exported the  **SOPS_KMS_ARN** env variable and my AWS credentials are present in ~/.aws/credentials.

When I run `sops -e my-file.yml` nothing happens and I get no feedback.

I cloned the repo and ran the same command using sops.go and this time it worked.

Any idea of what might be happening ?

### PR DESCRIPTION
**Pull request by autrilla**
First of all, urfave/cli doesn't print errors unless they're a `cli.ExitError`, which causes some errors to not be shown to the user. I've created a `toExitError` function that converts the error to a `cli.ExitError` if it isn't one.

Secondly, there were some cases of the `err` variable being overwritten by branches in main.go, which caused the error to also not be printed.

Third, the `--config` flag was not being used, and getting the Shamir threshold errored if no `.sops.yaml` config file was found.

Fixes #262

### CODE REVIEW

File: cmd/sops/main.go [hunk 1]
```diff
@@ -367,13 +367,15 @@ func main() {
 		var output []byte
 		var err error
 		if c.Bool("encrypt") {
-			keyGroups, err := keyGroups(c, fileName)
+			var groups []sops.KeyGroup
+			groups, err = keyGroups(c, fileName)
```
Comment (jvehent) [inline cmd/sops/main.go]: why not use
```go
groups, err := keyGroups(c, fileName)
```
