### PR TITLE
Fix KMS encryption context for backwards compatibility with SOPS 1.x

### LINKED ISSUE #190: KMS encryption context not backwards compatible
In SOPS 2.0 KMS encryption context is stored as a string value in the json output where the old python version used JSON Object to store encryption context.

```sh
❯ jq '.sops.kms | .[].context' encrypted-python
{
  "a": "b",
  "c": "d"
}
❯ jq '.sops.kms | .[].context' encrypted-go
"a:b,c:d"
```

The two outputs are incompatible with each other and reading an old SOPS encrypted file with SOPS 2.0 will cause a stack trace.

```
panic: interface conversion: interface is map[string]interface {}, not string [recovered]
	panic: interface conversion: interface is map[string]interface {}, not string

goroutine 1 [running]:
panic(0x46e220, 0xc420077b40)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.HandleAction.func1(0xc42012f7a8)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:473 +0x29e
panic(0x46e220, 0xc420077b40)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:458 +0x243
go.mozilla.org/sops/json.Store.kmsEntries(0xc420158120, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/json/store.go:316 +0x656
go.mozilla.org/sops/json.Store.UnmarshalMetadata(0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/json/store.go:279 +0x8f5
go.mozilla.org/sops/json.BinaryStore.UnmarshalMetadata(0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/json/store.go:61 +0x7c
go.mozilla.org/sops/json.(*BinaryStore).UnmarshalMetadata(0x7397c8, 0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:21 +0xb0
main.loadEncryptedFile(0xc4200b6dc0, 0x6fd380, 0x7397c8, 0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/cmd/sops/main.go:74 +0xa1
main.main.func1(0xc4200b6dc0, 0x0, 0x0)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/cmd/sops/main.go:227 +0x322
reflect.Value.call(0x44f060, 0x51eaa8, 0x13, 0x4de77e, 0x4, 0xc42012f768, 0x1, 0x1, 0xfe068, 0x4d3800, ...)
	/usr/local/Cellar/go/1.7.4/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x44f060, 0x51eaa8, 0x13, 0xc42012f768, 0x1, 0x1, 0x51e9e8, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/reflect/value.go:302 +0xa4
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x44f060, 0x51eaa8, 0xc4200b6dc0, 0x0, 0x0)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:482 +0x1e0
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420134000, 0xc42007c090, 0x3, 0x3, 0x0, 0x0)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:240 +0x596
main.main()
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/cmd/sops/main.go:284 +0xe0e
```

### PR DESCRIPTION
**Pull request by rouge8**
In SOPS 1.x, KMS encryption context was stored as a JSON object, but SOPS 2.0 stored it as a comma-separated list of key/value pairs:

```
$ jq '.sops.kms | .[].context' encrypted-python
{
  "a": "b",
  "c": "d"
}
> jq '.sops.kms | .[].context' encrypted-go
"a:b,c:d"
```

The two outputs are incompatible with each other and caused a stack trace when reading files encrypted with SOPS 1.x.

This patch restores read and output compatibility with SOPS 1.x.

Fixes #190.

This is the only Go I've ever written, so I can attempt to make any requested changed but I'm also okay with someone else polishing this. :)

### CODE REVIEW

File: kms/keysource.go [hunk 1]
```diff
@@ -162,37 +161,56 @@ func (key MasterKey) createSession() (*session.Session, error) {
...
-		kv := strings.Split(kv, ":")
-		if len(kv) != 2 {
+
+	switch in := in.(type) {
+	case map[string]interface{}:
+		if len(in) == 0 {
+			return nil
+		}
+		for k, v := range in {
+			var v = v.(string)
```
Comment (autrilla) [inline kms/keysource.go]: When casting, I would prefer it if you checked for an error and showed a warning, otherwise, this will panic. It should never happen, because this should never be manipulated by the user and a non-string should never wind up there. There are a bunch of unchecked casts in the codebase already, so I understand you might be copying our style, but in this case, you really shouldn't 😉 

Something like:

```go
value, ok := v.(string)
if !ok {
    fmt.Printf("[WARNING]: KMS Encryption Context contains a non-string key, context will not be used")
    return nil
}
```

File: kms/keysource.go [hunk 2]
```diff
@@ -162,37 +161,56 @@ func (key MasterKey) createSession() (*session.Session, error) {
...
+			out[k] = &v
+		}
+	case map[interface{}]interface{}:
+		if len(in) == 0 {
 			return nil
 		}
-		out[kv[0]] = &kv[1]
+		for k, v := range in {
+			var v = v.(string)
+			out[k.(string)] = &v
```
Comment (autrilla) [inline kms/keysource.go]: Same as above, both for the value and the key.

File: kms/keysource.go [hunk 3]
```diff
@@ -162,37 +161,56 @@ func (key MasterKey) createSession() (*session.Session, error) {
...
+		}
+	case string:
+		if in == "" {
+			return nil
+		}
+		for _, kv := range strings.Split(in, ",") {
+			kv := strings.Split(kv, ":")
+			if len(kv) != 2 {
+				return nil
```
Comment (autrilla) [inline kms/keysource.go]: I feel we should also show a warning here instead of silently skipping.

**Comment by jvehent** [comment]
I merged another PR that created conflicts with this one. Could you rebase against master?

**Comment by rouge8** [comment]
@jvehent @autrilla rebased and added error messages for types
